galaxy_info:
  author: Pedro Mora <Drop>
  description: Installs n (version manager for nodejs) and nodejs latest version.
  company: 01Talent

  license: MIT
  
  min_ansible_version: 2.1

  platforms:
   - name: Ubuntu 
     versions:
     - 22.04

  galaxy_tags: [nodejs, 01Talent]

dependencies: []
