---
# defaults file for golang
go_pkgs:                                                         
    - github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
    - github.com/cweill/gotests/gotests@latest
    - github.com/fatih/gomodifytags@latest
    - github.com/josharian/impl@latest
    - github.com/haya14busa/goplay/cmd/goplay@latest
    - github.com/go-delve/delve/cmd/dlv@latest
    - github.com/go-delve/delve/cmd/dlv@master
    - honnef.co/go/tools/cmd/staticcheck@latest
    - golang.org/x/tools/gopls@latest
    - mvdan.cc/gofumpt@latest
