- name: Ensure sftp 
  tags: [ssh]
  ansible.builtin.lineinfile:
    line: "Subsystem       sftp    internal-sftp"
    path: /etc/ssh/sshd_config
    regexp: '^Subsystem'

- name: Add bocal members public keys to the bocal user
  tags: [ssh]
  loop: "{{ extra_ssh_keys }}"
  ansible.builtin.lineinfile:
    path: /home/bocal/.ssh/authorized_keys
    line: "{{ item }}"
    state: present

- name: Restart sshd
  tags: [ssh]
  ansible.builtin.systemd:
    state: reloaded 
    name: sshd
